.core-defs:
  variables:
    JNI_PATH: libretro
    CORENAME: hatari

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

#Desktop
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default
  variables:
    MAKEFILE: Makefile.libretro

libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
  variables:
    MAKEFILE: Makefile.libretro
    
# Android
android-armeabi-v7a:
  extends:
    - .core-defs
    - .libretro-android-jni-armeabi-v7a

android-arm64-v8a:
  extends:
    - .core-defs
    - .libretro-android-jni-arm64-v8a

android-x86_64:
  extends:
    - .core-defs
    - .libretro-android-jni-x86_64
    
android-x86:
  extends:
    - .core-defs
    - .libretro-android-jni-x86

# Static
libretro-build-vita:
  extends:
    - .core-defs
    - .libretro-vita-static-retroarch-master
  variables:
    MAKEFILE: Makefile.libretro

before_script:
 - apt-get update -qq

build-normal:
 script:
 - apt-get install -y -qq cmake libsdl2-dev libpng-dev zlib1g-dev libudev-dev
 - mkdir build
 - cd build
 - CFLAGS="-Os -Werror" ../configure
 - make
 - make test

build-alt:
 script:
 - apt-get install -y -qq cmake libsdl1.2-dev portaudio19-dev libportmidi-dev
 - rm -rf /usr/include/zlib.h /usr/include/png.h /usr/include/readline*
 - ./configure --enable-old-uae-cpu --enable-small-mem --disable-dsp
               --disable-sdl2 --enable-debug --disable-tracing
 - make
 - make test

build-32bit:
 script:
 - dpkg --add-architecture i386
 - apt-get update -qq
 - apt-get install -y cmake gcc-multilib libgcc1:i386 libsdl2-dev:i386
                      zlib1g-dev:i386 libpng-dev:i386 libglib2.0-dev:i386
 - CFLAGS="-m32 -O2 -Werror" ./configure --enable-debug
 - make
 - file src/hatari | grep 32.bit
 - make test

build-clang:
 script:
 - apt-get install -y -qq cmake clang libsdl2-dev libpng-dev zlib1g-dev
                      libudev-dev portaudio19-dev libportmidi-dev tidy
 - CC="clang" CFLAGS="-O3 -Werror" ./configure --enable-debug
 - make
 - make test

build-mingw:
 image: fedora:latest
 before_script:
 - dnf update -y
 - dnf install -y cmake make gcc python-unversioned-command mingw32-gcc
                  mingw32-SDL2 mingw32-zlib
 script:
 - cmake -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain-mingw32-win64_32.cmake
         -DENABLE_WERROR:BOOL=1 .
 - make
